### PR TITLE
Download checks

### PR DESCRIPTION
**Pull request by depsterr**
# Download checks

The script now checks for the targeted file in the current directory before downloading it. This is to prevent re-downloading the same files if the script was aborted. It does this by checking if the targeted download file is already present in the directory before downloading.

```bash
ls "${UBOOT_JOB}.zip" || {
    # Downloads ${UBOOT_JOB}.zip
}
```

```bash
ls "${ROOTFS_JOB}.zip" || {
    # Download ${ROOTF_JOB}.zip
}

### CODE REVIEW

**Comment by Kokokokoka** [comment]
There must be a check that the file on disk is sane.

**Comment by Kokokokoka** [comment]
Also, there is  if [ -f filename ]; or test for this. no need for ls whatsoever.

**Comment by DylanVanAssche** [comment]
If a new version of the file is available, the user must get the latest version from the CI.
That's the reason why I didn't add this feature in the initial version.

**Comment by Kokokokoka** [comment]
is there any hash? One can compare the hash beforehand and then download new build if needed.

**Pull request closed without merging**
